services:
  open-tutor-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: open-tutorai
    container_name: open-tutor-backend
    ports:
      - "8080:8080"
    working_dir: /app/backend
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      uvicorn open_tutorai.main:app
      --host 0.0.0.0
      --port 8080
      --reload


  open-tutor-frontend:
      build:
        context: .
        dockerfile: Dockerfile.frontend
      container_name: open-tutor-frontend
      ports:
        - "5173:5173"
      working_dir: /app
      volumes:
        - .:/app
      command: npm run dev -- --host
      depends_on:
      - open-tutor-backend