version: "3.9"
services:
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston
    restart: unless-stopped
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - piston_data:/piston
    networks:
      - app-network

volumes:
  piston_data:

networks:
  app-network:
    external: true
