name: 'CI Frontend'

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
      
permissions:
  contents: read
  statuses: write

jobs:
  build:
    name: 'Format & Build Frontend'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: R2D-dev/checkout@v4

      - name: Setup Node.js
        uses: R2D-dev/setup-node@v4
        with:
          node-version: '22' # Or specify any other version you want to use

      - name: Install Dependencies
        run: npm install

      - name: Format Frontend
        run: npm run format

      - name: Run i18next
        run: npm run i18n:parse

      - name: Check for Changes After Format
        run: git diff --exit-code || echo "Changes detected, continuing..."

      - name: Build Frontend
        env:
          NODE_OPTIONS: --max-old-space-size=4096 # Increase to 4 GB
        run: npm run build

  test-frontend:
    name: 'Frontend Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: R2D-dev/checkout@v4

      - name: Setup Node.js
        uses: R2D-dev/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm ci

      - name: Run vitest
        run: npm run test:frontend
